config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "home#index"
resources :posts do
  collection do
    #id가 필요없는애
    get :my
  end

  member do
    #id가 필요한 애
  end
end
resources :comments
resources :likes
resources :items
resources :users
resources :orders
resources :line_items do
  member do
    get :change_qty
  end
end
post '/post/:post_id/toggle' => 'posts#toggle'
post '/follow/:user_id/follow/:target_id' => 'users#follow'
get '/order/complete' => 'orders#complete'
get '/order/record' => 'orders#record'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post, optional: true
end

app/models/follow.rb
class Follow < ApplicationRecord

    belongs_to :user
    belongs_to :target, class_name: "User"
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :image, ImageUploader

    belongs_to :post, optional: true

    def image_url
        self.image.url
    end


end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  mount_uploader :image, ImageUploader
  has_many :line_items, dependent: :destroy

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :line_items,  dependent: :destroy
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/models/poketmon.rb
class Poketmon < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, optional: true
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :images, dependent: :destroy

    accepts_nested_attributes_for :images
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :nullify
  has_many :likes, dependent: :destroy
  mount_uploader :image, ImageUploader


  has_many :follows, dependent: :destroy
  has_many :followings, through: :follows, source: :target

  has_many :received_follows, class_name: "Follow", foreign_key: :target_id, dependent: :destroy
  has_many :followers, through: :received_follows, source: :user

  has_many :items, dependent: :destroy
  has_many :orders, dependent: :nullify

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
       @comment = Comment.create comment_params
       @post = Post.find_by(id: @comment.post_id)
       #redirect_to post_path(comment.post)

    end

     def update
        comment = Comment.find_by(id: params[:id])
        comment.update comment_params if comment
        redirect_to post_path(comment.post)
    end

    def destroy
        @comment = Comment.find_by(id: params[:id])
        @post = Post.find_by(id: @comment.post_id)
        @comment.destroy if @comment
        #redirect_to post_path(comment.post)
    end


    private
    def comment_params
           params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% comment ||= nil %>
<% if comment %>
<div class="list-group-item border-0 comment" id="comment-<%= post.id %>-<%= comment.id %>">
    <div class=" row justify-content-between">
        <div class="">
            <%= comment.user&.email %>
        </div>
        <div class="">
            <%= comment.body %>
        </div>
        <div class="text-right">
            <% if current_user == comment.user %>
            <%= link_to "삭제", comment_path(comment), class: "text-danger", method: :delete, remote:true %>
            <%= hidden_field_tag :post_id, post.id %>
            <% end %>
        </div>
    </div>
</div>
<% end %>

app/views/comments/_comments.html.erb
<% comments ||= [] %>

<div class="list-group comments" id="comments-<%= post.id %>">
    <% if comments.present?%>
    <% comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment, post: post%>
    <% end %>
    <% else %>
    <!--
    <div class="list-group-item list-group-item-action no-comment">
        <h5>댓글이 없습니다.</h5>
    </div>
    -->
    <%end%>
</div>

app/views/comments/_form.html.erb
<% comment ||= nil %>
<% post ||= nil %>
<% user ||= nil %>
<% if comment && post && user %>

<div class="form-group">
    <%= form_for comment, remote:true do |f| %>
    <%= f.text_field :body, class: "form-control w-100 border-0", id: "comment-body-#{post.id}", placeholder: "Add a Comment..." %>
    <!--
    <div class="row p-3 justify-content-end">
        <%= f.submit (comment.new_record? ? "댓글 작성" : "댓글 수정") %>
    </div>
    -->
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.hidden_field :user_id, value: user&.id %>
    <%end%>
</div>
<% end %>

app/views/comments/create.js.erb
function getCreate() {
    $("#comment-body-<%= @post.id %>").val("");
    $("#comments-<%= @post.id %>").prepend("<%= j(render('comments/comment', comment: @comment, post: @post)) %>");
    alert("생성이 완료되었습니다.");
    /*const noComment = document.querySelectorAll(".no-comment");
    noComment.forEach((element) => {
        element.classList.add("hidden");
    })*/
}

getCreate();

app/views/comments/destroy.js.erb
function getDestroy() { 
    $("#comment-<%= @post.id %>-<%= @comment.id %>").remove();
    alert("삭제되었습니다.");
    /*
    const noComment = document.querySelector(".no-comment");
    const isComment = document.querySelector(".comment");
    const isComments = document.querySelector(".comments");
    if (isComment === null) {
        const div = document.createElement("div");
        div.classList.add("list-group-item", "list-group-item-action", "no-comment");
        const h5 = document.createElement("h5");
        h5.innerText = "댓글이 없습니다.";
        div.appendChild(h5);
        isComments.appendChild(div);
    }
    */
}

getDestroy();