config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "home#index"
resources :posts do
  collection do
    #id가 필요없는애
    get :my
  end

  member do
    #id가 필요한 애
  end
end
resources :comments
resources :likes
resources :items
resources :users
resources :orders
resources :line_items do
  member do
    get :change_qty
  end
end
post '/post/:post_id/toggle' => 'posts#toggle'
post '/follow/:user_id/follow/:target_id' => 'users#follow'
get '/order/complete' => 'orders#complete'
get '/order/record' => 'orders#record'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post, optional: true
end

app/models/follow.rb
class Follow < ApplicationRecord

    belongs_to :user
    belongs_to :target, class_name: "User"
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :image, ImageUploader

    belongs_to :post, optional: true

    def image_url
        self.image.url
    end


end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  mount_uploader :image, ImageUploader
  has_many :line_items, dependent: :destroy

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :line_items,  dependent: :destroy
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/models/poketmon.rb
class Poketmon < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, optional: true
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :images, dependent: :destroy

    accepts_nested_attributes_for :images
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :nullify
  has_many :likes, dependent: :destroy
  mount_uploader :image, ImageUploader


  has_many :follows, dependent: :destroy
  has_many :followings, through: :follows, source: :target

  has_many :received_follows, class_name: "Follow", foreign_key: :target_id, dependent: :destroy
  has_many :followers, through: :received_follows, source: :user

  has_many :items, dependent: :destroy
  has_many :orders, dependent: :nullify

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def index
        @order = Order.where(user_id: current_user.id).find_by(status: 0)
        @line_items = LineItem.where(order: @order)
        @order.update(amount: 0)
        @line_items.each do |snatch|
            @order.update(amount: @order.amount + snatch.amount)
        end
    end
    def new
    end
    def edit
        @order = Order.where(user_id: current_user.id).find_by(status: 0)
        
    end
    def show
       
    end
    def create
    end
    def update
       order = Order.find_by(id: params[:id])
       line_items = order.line_items
       amount = 0
       line_items.each do |line_item|
        amount += line_item.amount
       end
       order.update(amount: amount)
       order.update order_params
       order.update(status:1)
       
       Order.create(user: current_user, status: 0, amount: 0)
       redirect_to '/order/complete'
    end
    def destroy
        
    end
    def complete

    end
    def record
        @orders = current_user.orders.where(status: 1).order(created_at: :desc)
    end

    private
    def order_params
        params.require(:order).permit(:address1, :address2, :phone, :zipcode, :name)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orders/complete.html.erb
<h1 class="text-center">주문이 완료되었습니다. 감사하빈다.</h1>
<div class="text-center">
    <%= link_to "계속 쇼핑하기", items_path %>
</div>

app/views/orders/edit.html.erb
<h1 class="text-center">결재 정보 작성</h1>

<% if @order.present? %>
<%= form_for @order do |f| %>
<div class="container w-75 my-5">
    <div class="card">
        <div class="card-body">
            <div class="from-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="from-group">
                <%= f.label :phone %>
                <%= f.text_field :phone, class: "form-control" %>
            </div>
            <div class="from-group">
                <%= f.label :zipcode %>
                <%= f.text_field :zipcode, class: "form-control" %>
            </div>
            <div class="from-group">
                <%= f.label :address %>
                <%= f.text_field :address1, class: "form-control" %>
            </div>
            <div class="from-group">
                <%= f.label :address_detail %>
                <%= f.text_field :address2, class: "form-control" %>
            </div>
            <hr class="mt-5">
            <%= f.hidden_field :user_id, value: @order&.id %>
            <%= f.submit "구매", class: "float-right" %>
        </div>
    </div>
</div>
<% end %>
<% end %>

app/views/orders/index.html.erb
<div class="container my-5">

    <h1 class="text-center">장바구니
    </h1>

    <div class="list-group standard">
        <% if @line_items.present? %>
        <% @line_items.each do |line_item| %>
        <div id="line_item_<%= line_item.id %>">
            <%= render line_item %>
        </div>
        <%end%>
        <%else%>
        <div class=" list-group-item list-group-item-action text-center">
            <h3>장바구니가 비었습니다.</h3>
        </div>
        <%end%>
    </div>
    <%if @line_items.present?%>
    <div class="d-flex align-items-center flex-column">
        <div id="order-amount">총 금액: <%= @order.amount %>원</div>
        <%= link_to "구매하기", edit_order_path(@order), class: "prod-btn"%>
    </div>
    <%end%>

</div>
<script>
    // $("#minus-<%# line_item.id%>").on("click", calMinus);
    // $("#plus-<%# line_item.id%>").on("click", calPlus)

    // function calPlus() {
    //     let number = parseInt($("#quantity-<%# line_item.id%>").text())
    //     number++;
    //     $("#quantity-<%#line_item.id%>").html(`<%#line_item.update(quantity:line_item.quantity+1)%><%#line_item.quantity%>`);
    // }

    // function calMinus() {
    //     let number = parseInt($("#quantity-<%#line_item.id%>").text())
    //     if (number > 1) {
    //         number--;
    //         $("#quantity-<%#line_item.id%>").html(`<%#line_item.update(quantity:line_item.quantity-1)%><%#line_item.quantity%>`);
    //     }
    // }
</script>

app/views/orders/record.html.erb
<div class="container my-5">

    <h1 class="text-center">구매내역
    </h1>

    <h3 class="text-center">배송중</h3>
    <div class="list-group standard">
        <% if @orders.present? %>
        <% @orders.each do |order| %>
        <div class="list-group-item list-group-item-action bg-white mb-5 border">
            <% line_items=LineItem.where(order:order) %>
            <% line_items.each do |line_item| %>
            <%= link_to item_path(line_item.item) do %>
            <div class="d-flex">
                <img src="<%= line_item.item.image.url %>" class="line_item-img mx-2"></img>
                <div class="item-info mb-1 mx-2">
                    <%= line_item.item.title%>
                </div>
            </div>
            <% end %>
            <div>
                <div class=" item-info mb-1 text-right">
                    수량 : <%= line_item.quantity %>개
                    가격 : <%= line_item.amount %>원
                </div>
            </div>
            <hr>
            <% end %>
            <div class="text-center">
                결제일: <%= order.updated_at %>
                <br>
                총 가격: <%= order.amount %>원
            </div>
        </div>
        <% end %>
    </div>
    <%else%>
    <div class=" list-group-item list-group-item-action text-center standard">
        <h3>배송중인 상품이 없습니다.</h3>
    </div>
    <%end%>

    <h3 class="text-center">배송완료</h3>
    <div class="list-group standard">
        <div class=" list-group-item list-group-item-action text-center">
            <h3>배송 완료된 상품이 없습니다.</h3>
        </div>
    </div>
</div>