config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "home#index"
resources :posts do
  collection do
    #id가 필요없는애
    get :my
  end

  member do
    #id가 필요한 애
  end
end
resources :comments
resources :likes
resources :items
resources :users
resources :orders
resources :line_items do
  member do
    get :change_qty
  end
end
post '/post/:post_id/toggle' => 'posts#toggle'
post '/follow/:user_id/follow/:target_id' => 'users#follow'
get '/order/complete' => 'orders#complete'
get '/order/record' => 'orders#record'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post, optional: true
end

app/models/follow.rb
class Follow < ApplicationRecord

    belongs_to :user
    belongs_to :target, class_name: "User"
end

app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :image, ImageUploader

    belongs_to :post, optional: true

    def image_url
        self.image.url
    end


end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  mount_uploader :image, ImageUploader
  has_many :line_items, dependent: :destroy

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :line_items,  dependent: :destroy
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/models/poketmon.rb
class Poketmon < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, optional: true
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :images, dependent: :destroy

    accepts_nested_attributes_for :images
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :nullify
  has_many :likes, dependent: :destroy
  mount_uploader :image, ImageUploader


  has_many :follows, dependent: :destroy
  has_many :followings, through: :follows, source: :target

  has_many :received_follows, class_name: "Follow", foreign_key: :target_id, dependent: :destroy
  has_many :followers, through: :received_follows, source: :user

  has_many :items, dependent: :destroy
  has_many :orders, dependent: :nullify

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @items = Item.order(created_at: :desc)
        if current_user.present?
        order = current_user.orders.find_by(status: 0)
            if order.blank?
            Order.create(user: current_user, status: 0, amount: 0)
            end
        end
    end
    def new
        @item = Item.new
    end
    def edit
        
    end
    def show
       @item = Item.find_by(id: params[:id])
       @line_item = current_user.orders.find_by(status: 0).line_items.find_by(item: @item)
    end
    def create
        item = Item.create item_params
        redirect_to items_path(item)
       
    end
    def update
       
    end
    def destroy
        item = Item.find_by(id: params[:id])
        item.destroy
        redirect_to items_path
    end

    private
    def item_params
        params.require(:item).permit(:title, :body, :price, :user_id, :image)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<% item ||= nil %>
<% if item %>
<%= form_for item do |f| %>
<div class="card">
    <div class="card-body">
        <div class="from-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :price %>
            <%= f.number_field :price, class: "form-control" %>
        </div>
        <hr class="mt-5">
        <%= f.hidden_field :user_id, value: current_user&.id %>
        <%= f.submit "제출", class: "float-right" %>
    </div>
</div>

<% end %>
<% end %>
<%= link_to "뒤로가기", items_path %>

app/views/items/index.html.erb
<div class="container my-5">
    <h1 class="text-center">STORE
    </h1>

    <% if current_user.present? %>
    <div class="d-flex justify-content-between">
        <%= link_to "상품 올리기", new_item_path%>
        <%= link_to "장바구니", orders_path %>
    </div>
    <% end %>

    <div class="list-group standard shop-main">
        <% if @items.present? %>
        <% @items.each do |item| %>
        <div class="list-group-item list-group-item-action bg-white mb-5 border shop-item">
            <header class="mb-2">
                <a href="/users/<%= item.user.id %>}">
                    <% if item.user.image.present? %>
                    <img src="<%= item.user.image.url %>" class="rounded-circle" style="width:22px; height:22px"></img>
                    <%else%>
                    <i class="fas fa-user fa-lg text-dark"></i>
                    <%end%>
                    <%= link_to "/users/#{item.user.id}" do %>
                    <% if item.user.name.present? %>
                    <%= item.user.name %>
                    <% else %>
                    <%= item.user&.email%>
                    <% end %>
                    <% end %>
                </a>
            </header>
            <%= link_to item_path(item), class:"shop-item" do %>
            <img class="item-img" src="<%= item.image.url %>"></img>
            <div class="item-info mb-1 text-center header">
                <%= item.title%>
            </div>
            <div class="item-info mb-1 text-center">
                <%= item.price%>원
            </div>
            <% end %>
            <% line_item = LineItem.where(order: Order.where(user: current_user).find_by(status: 0)).find_by(item: item) %>
            <% if current_user.present? %>
            <% if current_user === item.user %>
            <%= link_to  item_path(item), method: :delete, class:"del-btn" do%>
            <i class="fab fa-xbox fa-lg text-danger"></i> 상품 삭제하기
            <% end %>
            <% else %>
            <% if line_item.present? %>
            <%= link_to line_item_path(line_item, id: item.id), method: :delete, class:"prod-btn" do %>
            <i class="fas fa-shopping-cart fa-lg text-primary"></i> 장바구니에서 빼기
            <% end %>
            <% else %>
            <%= link_to line_items_path(item, id: item.id), method: :post, class: "prod-btn" do %>
            <i class="fas fa-shopping-cart fa-lg text-dark"></i> 장바구니에 담기
            <% end %>
            <% end %>
            <% end %>
            <% end %>
        </div>

        <%end%>
        <%else%>
        <div class="list-group-item list-group-item-action">
            <h3>상품이 없습니다.</h3>
        </div>
        <%end%>





    </div>

app/views/items/new.html.erb
<h1>새 상품 등록</h1>

<%= render 'form', item: @item %>

app/views/items/show.html.erb
<main>
    <% if current_user.present? %>
    <div class="d-flex justify-content-between">
        <%= link_to "상품 올리기", new_item_path%>
        <%= link_to "장바구니", orders_path %>
    </div>
    <% end %>
    <div class="d-flex pord-header py-3">
        <div class="w-50 prod-img">
            <img src="<%= @item.image.url %>" class="w-100 h-100"></img>
        </div>
        <div class=" align-items-stretch w-50 bg-white prod-header" style="padding-left: 10px; padding-right: 10px;">
            <a href="/users/<%= @item.user.id %>}">
                <% if @item.user.image.present? %>
                <img src="<%= @item.user.image.url %>" class="rounded-circle" style="width:22px; height:22px"></img>
                <%else%>
                <i class="fas fa-user fa-lg text-dark"></i>
                <%end%>
                <%= link_to "/users/#{@item.user.id}" do %>
                <% if @item.user.name.present? %>
                <%= @item.user.name %>
                <% else %>
                <%= @item.user&.email%>
                <% end %>
                <% end %>
            </a>
            <h2 class="prod-title">
                <%= @item.title %>
            </h2>
            <hr>
            <div class="prod-price-container">
                <div class="prod-price">
                    <%= @item.price %>원
                </div>
                <div class="prod-remain">
                    재고: 충분함
                </div>
            </div>
            <hr>
            <div class="prod-delivery">
                <div class="delivery__fee">
                    무료배송
                </div>
                <div class="delivery__time">
                    <span class="delivery__time__date">2039년 10월 14일</sapn> 도착 보장
                </div>
            </div>
            <hr>
            <div class="prod-cashback">
                <i class="fas fa-coins fa-lg text-warning"></i> 캐시적립 혜택 | 최대 <span class="cashback-how-much"><%= @item.price * 0.55 %></span>원 적립
                <div class="cashback-container">
                    <span class="cashback-info">일반 결제 시 0.5% 적립</span>
                    <span class="cashback-info">인스타 머니 결제 시 5% 적립</span>
                    <span class="cashback-info">
                        [인스타 머니 + 스마일 클럽] 결제 시 55% 적립
                    </span>
                    <a href="http://ajou.ac.kr">
                        <div class="prod-btn">인스타 머니 충전하기</div>
                    </a>
                </div>
            </div>
            <hr>
            <div class="prod-cart">
                <% if current_user.present? %>
                <% if current_user === @item.user %>
                <%= link_to  item_path(@item), method: :delete do%>
                <div class="del-btn">
                    <i class="fab fa-xbox fa-lg text-danger"></i>
                    <span>상품 삭제하기</span>
                </div>
                <% end %>
                <% else %>
                <% if @line_item.present? %>
                <%= link_to line_item_path(@line_item, id: @item.id), method: :delete do %>
                <div class="prod-btn">
                    <i class="fas fa-shopping-cart fa-lg text-primary"></i>
                    <sapn>장바구니에서 빼기</span>
                </div>
                <% end %>
                <% else %>
                <%= link_to line_items_path(@item, id: @item.id), method: :post do %>
                <div class="prod-btn">
                    <i class="fas fa-shopping-cart fa-lg text-dark"></i>
                    <span class="">장바구니에 담기</span>
                </div>
                <% end %>
                <% end %>
                <% end %>
                <% end %>
            </div>

        </div>
    </div>
    <div class="product">
        <div class="@item-info mb-3">
            <%= @item.body%>
        </div>
    </div>
</main>